#!/bin/sh

## module to read meta in header of md file
## usage: 
##      md-header [md_filepath]

[ "$#" -ne 1 ] && { echo "Incorrect usage"; exit 1; }

# usage: getprop [path] [prop]
getprop() {
    sed -nE "s/^-- $2: (.*)$/\1/p" "$1"
}

export ARTICLE_TITLE=`getprop "$1" name`
export PUBLISHED_DATE=`getprop "$1" published`
export DESCRIPTION=`getprop "$1" description`
export USERLOCAL1=`getprop "$1" userlocal1`
export USERLOCAL2=`getprop "$1" userlocal2`
# this only works when this script is called from pinopress script, as it inherits the required env variables. careful with this one, it's a bit hacky
export ARTICLE_URL="$SITEURL/$ARTICLE_PATH/$(echo $(basename "$1") | sed -e 's/\(.*\)\.md/\1\.html/')"
